--- #YAML:1.0
name:                CAM-PDF-Annot
version:             0.06
abstract:            Perl extension for appending annotations on PDFs
license:             ~
author:              
    - DONATOAZ <donatoaz@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
